spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: sa
    hikari.connection-test-query: SELECT 1
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/rootChangelog.xml
  jpa:
    show-sql: true
