spring:
  mongodb:
    embedded:
      features:
  data:
    mongodb:
      host: 0.0.0.0
#      port: 27017
#      database: test
#      username: myusername
#      password: mypassword
#      uri: mongodb://myusername:mypassword@localhost:27017/nullbeans
#      authentication-database: admin

