INSERT INTO AUTHORS (`NAME`) VALUES ('Николай Гоголь');
INSERT INTO AUTHORS (`NAME`) VALUES ('Тургенев Иван');
INSERT INTO AUTHORS (`NAME`) VALUES ('Чехов Антон');

INSERT INTO GENRES (`NAME`) VALUES ('Повесть');
INSERT INTO GENRES (`NAME`) VALUES ('Роман');
INSERT INTO GENRES (`NAME`) VALUES ('Рассказ');

INSERT INTO BOOKS (`NAME`, AUTHORID, GENREID, PAGE) VALUES ('Тарас Бульба', (SELECT ID FROM AUTHORS WHERE `NAME` = 'Николай Гоголь'), (SELECT ID FROM GENRES WHERE `NAME` = 'Повесть'), 300);
INSERT INTO BOOKS (`NAME`, AUTHORID, GENREID, PAGE) VALUES ('Отцы и дети', (SELECT ID FROM AUTHORS WHERE `NAME` = 'Тургенев Иван'), (SELECT ID FROM GENRES WHERE `NAME` = 'Роман'), 500);
INSERT INTO BOOKS (`NAME`, AUTHORID, GENREID, PAGE) VALUES ('Дама с собачкой', (SELECT ID FROM AUTHORS WHERE `NAME` = 'Чехов Антон'), (SELECT ID FROM GENRES WHERE `NAME` = 'Рассказ'), 180);