DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME VARCHAR(255), AUTHORID BIGINT, GENREID BIGINT, PAGE INTEGER);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME VARCHAR(255));

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME VARCHAR(255));